languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = "true"
enableEmoji = "true"

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://cedwards.org/"
title = "Christer Edwards"

[params]
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#aaa"
colorSecondary = "#499eb4"
colorIconPrimary = "#fff"
colorIconBackground = "#499eb4"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#499eb4"
pages = 2
